# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-merge-conflict

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      exclude: migrations
      args: [--profile, black, --line-length=79]

- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
    - id: flake8
      exclude: (migrations|backend/family_budget/settings/)
      additional_dependencies:
        - flake8-docstrings

- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
    - id: black
      exclude: (migrations|backend/family_budget/settings/)
      args: [--line-length=79]

- repo: local
  hooks:
    - id: export-requirements
      name: Export requirements.txt
      language: system
      pass_filenames: false
      entry: poetry export --without-hashes --with dev --output backend/requirements.txt
      files: ^(pyproject.toml|poetry.lock)$
