name: Check migrations

on:
  pull_request:
    branches:
      - backend
      - develop

jobs:
  migrations:
    name: Check migrations
    runs-on: ubuntu-latest
    steps:
    -
      name: Check out the repo
      uses: actions/checkout@v2
    -
      name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.7
    -
      name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./backend/requirements.txt
    -
      name: Make migrations
      run: python ./backend/manage.py makemigrations --settings family_budget.settings.migrate_test --check --dry-run
